// Copyright (c) Royal Apps. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.
// RoyalTerminal.Rendering.Skia - Full terminal shader package model.

namespace RoyalTerminal.Avalonia.Rendering;

/// <summary>
/// Identifies where a shader resource is supplied from.
/// </summary>
public enum TerminalShaderResourceSource
{
    /// <summary>Resource is supplied by RoyalTerminal.</summary>
    BuiltIn,

    /// <summary>Resource is supplied by the host application.</summary>
    External,

    /// <summary>Resource is produced by an earlier pass.</summary>
    PassOutput,

    /// <summary>Resource is taken from frame history.</summary>
    History,

    /// <summary>Resource is generated by the shader runtime.</summary>
    Generated,
}
