<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <DefineConstants>$(DefineConstants);ROYALTERMINAL_OUTPUT_LEASES</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RoyalTerminal.GhosttySharp\RoyalTerminal.GhosttySharp.csproj" />
    <ProjectReference Include="..\..\src\RoyalTerminal.GhosttySharp.Native.OSX\RoyalTerminal.GhosttySharp.Native.OSX.csproj" Condition="$([MSBuild]::IsOSPlatform('OSX'))" />
    <ProjectReference Include="..\..\src\RoyalTerminal.GhosttySharp.Native.Win64\RoyalTerminal.GhosttySharp.Native.Win64.csproj" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
    <ProjectReference Include="..\..\src\RoyalTerminal.GhosttySharp.Native.Linux64\RoyalTerminal.GhosttySharp.Native.Linux64.csproj" Condition="$([MSBuild]::IsOSPlatform('Linux'))" />
    <ProjectReference Include="..\..\src\RoyalTerminal.Unicode\RoyalTerminal.Unicode.csproj" />
    <ProjectReference Include="..\..\src\RoyalTerminal.Rendering.Skia\RoyalTerminal.Rendering.Skia.csproj" />
    <ProjectReference Include="..\..\src\RoyalTerminal.Terminal.Pty.Unix\RoyalTerminal.Terminal.Pty.Unix.csproj" />
  </ItemGroup>

  <Import Project="..\..\src\RoyalTerminal.GhosttySharp.Native.OSX\build\RoyalTerminal.GhosttySharp.Native.OSX.targets" Condition="$([MSBuild]::IsOSPlatform('OSX'))" />
  <Import Project="..\..\src\RoyalTerminal.GhosttySharp.Native.Win64\build\RoyalTerminal.GhosttySharp.Native.Win64.targets" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
  <Import Project="..\..\src\RoyalTerminal.GhosttySharp.Native.Linux64\build\RoyalTerminal.GhosttySharp.Native.Linux64.targets" Condition="$([MSBuild]::IsOSPlatform('Linux'))" />

</Project>
