#!/usr/bin/env python3
"""Generate the immutable managed X11 table from the pinned Ghostty rgb.txt."""

import argparse
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "external/ghostty/src/terminal/res/rgb.txt"
OUTPUT = ROOT / "src/RoyalTerminal.Terminal.Vt.Managed/Terminal/ManagedColorParser.Generated.cs"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = SOURCE.read_text(encoding="ascii")
    entries = {}
    for line in source.splitlines():
        if not line:
            continue
        r, g, b, name = line.split(maxsplit=3)
        name = name.lower()
        color = (int(r) << 16) | (int(g) << 8) | int(b)
        if name in entries and entries[name] != color:
            raise ValueError(f"Conflicting X11 color: {name}")
        entries[name] = color
    lines = [
        "// Copyright (c) Royal Apps. All rights reserved.",
        "// Licensed under the MIT license. See LICENSE file in the project root for details.",
        "// <auto-generated />",
        "// Source: Ghostty src/terminal/res/rgb.txt (X11 color data).",
        f"// Normalized source SHA-256: {hashlib.sha256(source.encode('ascii')).hexdigest()}",
        "using System.Collections.Frozen;",
        "",
        "namespace RoyalTerminal.Terminal;",
        "",
        "internal static partial class ManagedColorParser",
        "{",
        "    private static readonly FrozenDictionary<string, uint> NamedColors =",
        "        new Dictionary<string, uint>(StringComparer.OrdinalIgnoreCase)",
        "        {",
    ]
    for name, color in sorted(entries.items()):
        if not all(c.isalpha() or c.isdigit() or c == " " for c in name):
            raise ValueError(f"Unexpected X11 key: {name}")
        lines.append(f'            ["{name}"] = 0xFF{color:06X},')
    lines += ["        }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);", "}", ""]
    result = "\n".join(lines)
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != result:
            raise SystemExit("Managed X11 table is stale; regenerate it.")
    else:
        OUTPUT.write_text(result, encoding="utf-8")
    print(f"Verified {len(entries)} unique X11 color names" if args.check else f"Generated {len(entries)} unique X11 color names")


if __name__ == "__main__":
    main()
