#!/usr/bin/env python3
"""Generate the managed XTGETTCAP table from Ghostty's terminfo source."""

from __future__ import annotations

import argparse
import ast
import pathlib
import re


ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "external/ghostty/src/terminfo/ghostty.zig"
OUTPUT = ROOT / "src/RoyalTerminal.Terminal.Vt.Managed/Terminal/GhosttyXtgettcap.Generated.cs"
ENTRY = re.compile(
    r'^\s*\.\{ \.name = (?P<name>"(?:\\.|[^"\\])*")'
    r', \.value = \.\{ \.(?P<kind>boolean|numeric|string) = (?P<value>.*?) \} \},\s*$'
)


def zig_string(token: str) -> str:
    return ast.literal_eval(token)


def response_value(kind: str, token: str) -> bytes | None:
    if kind == "boolean":
        return None
    if kind == "numeric":
        return str(int(token)).encode("ascii")

    value = zig_string(token)
    if "%" not in value:
        value = value.replace(r"\E", "\x1b")
        while value.startswith("^") and len(value) >= 2:
            control = 0x7F if value[1] == "?" else ord(value[1]) - 64
            value = chr(control) + value[2:]
    return value.encode("utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the committed generated file is stale",
    )
    arguments = parser.parse_args()
    entries: dict[str, bytes | None] = {
        "Co": b"256",
        "RGB": b"8",
    }
    for line in SOURCE.read_text(encoding="utf-8").splitlines():
        if ".{ .name = " not in line:
            continue
        match = ENTRY.match(line)
        if match is None:
            raise RuntimeError(f"Unsupported Ghostty terminfo entry: {line}")
        name = zig_string(match.group("name"))
        entries[name] = response_value(match.group("kind"), match.group("value"))

    if len(entries) != 272:
        raise RuntimeError(f"Expected 272 generated capabilities, found {len(entries)}")

    lines = [
        "// Copyright (c) Royal Apps. All rights reserved.",
        "// Licensed under the MIT license. See LICENSE file in the project root for details.",
        "// <auto-generated />",
        "#nullable enable",
        "",
        "using System.Collections.Frozen;",
        "",
        "namespace RoyalTerminal.Terminal;",
        "",
        "internal static partial class GhosttyXtgettcap",
        "{",
        "    private static readonly FrozenDictionary<string, string?> Capabilities =",
        "        new Dictionary<string, string?>(StringComparer.Ordinal)",
        "        {",
    ]
    for name in sorted(entries):
        key = name.encode("utf-8").hex().upper()
        value = entries[name]
        rendered = "null" if value is None else f'"{value.hex().upper()}"'
        lines.append(f'            ["{key}"] = {rendered},')
    lines.extend(
        [
            "        }.ToFrozenDictionary(StringComparer.Ordinal);",
            "}",
            "",
        ]
    )
    content = "\n".join(lines)
    if arguments.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit(
                "GhosttyXtgettcap.Generated.cs is stale; run "
                "scripts/generate-ghostty-xtgettcap.py"
            )
        return

    OUTPUT.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
